[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "opal_fetcher_test_dynamodb"
version = "0.1.3" 
authors = [{name = "rola", email = "rjia41@gatech.edu"}]
description = "A short description of your package"
readme = "README.md"
license = {file = "LICENSE"}
requires-python = ">=3.6"
dependencies = [
    "boto3",
    "opal-common",
    "cachetools",
    "pydantic",
    "flask"
]
